Repository refactor-group/refactor-platform-fe, pull requests merged in 2024-12, with the labels that each got.

#51 Add Dockerfile
  .env
  Dockerfile
  next.config.mjs
  package-lock.json
  package.json
  src/lib/api/actions.ts
  src/lib/api/agreements.ts
  src/lib/api/coaching-relationships.ts
  src/lib/api/coaching-sessions.ts
  src/lib/api/notes.ts
  src/lib/api/organizations.ts
  src/lib/api/overarching-goals.ts
  src/lib/api/user-session.ts
  src/site.config.ts
Labels: enhancement, feature work

#52 Coaching session fast switch select component
  src/app/coaching-sessions/[id]/page.tsx
  src/components/ui/coaching-session-selector.tsx
  src/components/ui/coaching-sessions/overarching-goal-container.tsx
  src/components/ui/dashboard/select-coaching-session.tsx
Labels: enhancement, feature work

#53 All environment variables for the dockerized application are set by the backend
  .env
  Dockerfile
Labels: enhancement

#54 Some final tweaks for 1.0-rc1 release
  src/app/coaching-sessions/[id]/layout.tsx
  src/app/coaching-sessions/[id]/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/login/page.tsx
  src/components/ui/coaching-sessions/actions-list.tsx
  src/components/ui/coaching-sessions/agreements-list.tsx
  src/components/ui/site-header.tsx
  src/lib/api/overarching-goals.ts
  src/types/overarching-goal.ts
Labels: enhancement, bug fix

#56 Improve dashboard & coaching session page data fetching and caching
  next.config.mjs
  package-lock.json
  package.json
  src/app/coaching-sessions/[id]/page.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/coaching-relationship-selector.tsx
  src/components/ui/coaching-session-selector.tsx
  src/components/ui/coaching-sessions/actions-list.tsx
  src/components/ui/coaching-sessions/coaching-session-title.tsx
  src/components/ui/coaching-sessions/overarching-goal-container.tsx
  src/components/ui/dashboard/select-coaching-session.tsx
  src/components/ui/main-nav-menu.tsx
  src/components/ui/organization-selector.tsx
  src/components/ui/providers.tsx
  src/components/ui/user-nav.tsx
  src/lib/api/coaching-relationships.ts
  src/lib/api/coaching-sessions.ts
  src/lib/api/organizations.ts
  src/lib/providers/app-state-store-provider.tsx
  src/lib/providers/auth-store-provider.tsx
  src/lib/providers/coaching-relationship-state-store-provider.tsx
  src/lib/providers/coaching-session-state-store-provider.tsx
  src/lib/providers/organization-state-store-provider.tsx
  src/lib/providers/root-layout-providers.tsx
  src/lib/stores/app-state-store.ts
  src/lib/stores/auth-store.ts
  src/lib/stores/coaching-relationship-state-store.ts
  src/lib/stores/coaching-session-state-store.ts
  src/lib/stores/organization-state-store.ts
  tsconfig.json
Labels: enhancement

#58 Restores the code block style functionality for coaching Notes
  src/styles/code-block.scss
  src/styles/styles.scss
Labels: bug fix

#60 Add the OverarchingGoal.title to the CoachingSessionSelector component
  src/components/ui/coaching-session-selector.tsx
  src/lib/api/overarching-goals.ts
  src/lib/providers/overarching-goal-state-store-provider.tsx
  src/lib/providers/root-layout-providers.tsx
  src/lib/stores/coaching-session-state-store.ts
  src/lib/stores/overarching-goal-state-store.ts
Labels: enhancement, feature work
