Repository refactor-group/refactor-platform-fe, pull requests merged in 2025-06, with the labels that each got.

#121 npm update
  package-lock.json
Labels: security

#127 Reduce the minimum width on the CoachingSessionList component
  src/components/ui/dashboard/coaching-session-list.tsx
Labels: enhancement

#125 Get https working for production deployment
  .env
  .github/workflows/build_and_push_nonproduction_images.yml
  .github/workflows/build_and_push_production_images.yml
  .github/workflows/deploy_to_do.yml
  .gitignore
  Dockerfile
  src/lib/api/user-sessions.ts
  src/site.config.ts
Labels: enhancement, infrastructure

#132 Handle an invalid login error case
  src/app/page.tsx
  src/components/ui/login/user-auth-form.tsx
  src/lib/api/entity-api.ts
  src/types/general.ts
Labels: bug fix

#124 Add the concept of user roles
  src/app/organizations/[id]/members/layout.tsx
  src/components/ui/coaching-relationship-selector.tsx
  src/components/ui/coaching-session.tsx
  src/components/ui/dashboard/add-entities.tsx
  src/components/ui/members/add-member-dialog.tsx
  src/components/ui/members/member-card.tsx
  src/components/ui/members/member-container.tsx
  src/components/ui/members/member-list.tsx
  src/components/ui/members/profile-info-update-form.tsx
  src/lib/api/coaching-relationships.ts
  src/lib/stores/auth-store.ts
  src/lib/stores/coaching-relationship-state-store.ts
  src/types/coaching_relationship.ts
  src/types/session-title.ts
  src/types/user-session.ts
  src/types/user.ts
Labels: enhancement

#131 Add tiptap doc loading indicator
  package-lock.json
  package.json
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/members/member-card.tsx
  src/components/ui/members/member-container.tsx
  src/components/ui/progress.tsx
Labels: enhancement

#139 Disable any current keyboard shortcut for toggling the sidebar
  src/components/ui/sidebar.tsx
Labels: bug fix
