Repository refactor-group/refactor-platform-fe, pull requests merged in 2025-03, with the labels that each got.

#73 collab cursor work
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/coaching-sessions/coaching-notes/extensions.tsx
  src/styles/styles.scss
Labels: enhancement

#72 Refactor Organization entity hooks and API to backend CRUD endpoints
  .env
  src/components/ui/organization-selector.tsx
  src/lib/api/entity-api.ts
  src/lib/api/organizations.ts
  src/types/organization.ts
Labels: enhancement

#75 Move login UI to index route & temp remove GitHub Oauth
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/ui/user-nav.tsx
  src/components/user-auth-form.tsx
Labels: enhancement

#77 Add stable TipTap cursor collaboration extension
  package-lock.json
  package.json
  src/app/coaching-sessions/[id]/page.tsx
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/coaching-sessions/coaching-notes/extensions.tsx
  src/styles/styles.scss
Labels: enhancement

#76 Add a middleware layer, handle optimistic auth check on basic routes
  src/lib/api/user-session.ts
  src/lib/providers/auth-store-provider.tsx
  src/lib/stores/auth-store.ts
  src/middleware.ts
Labels: enhancement

#82 Set error state with message rather than with error object
  src/components/user-auth-form.tsx
Labels: bug fix

#83 Cosmetic update for coaching session title
  src/components/ui/coaching-sessions/coaching-session-title.tsx
  src/site.config.ts
Labels: enhancement

#74 Refactor other entity API functions and hooks to use new pattern
  src/components/ui/coaching-relationship-selector.tsx
  src/components/ui/coaching-session-selector.tsx
  src/components/ui/coaching-session.tsx
  src/components/ui/coaching-sessions/actions-list.tsx
  src/components/ui/coaching-sessions/agreements-list.tsx
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/coaching-sessions/overarching-goal-container.tsx
  src/components/ui/dashboard/coaching-session-list.tsx
  src/components/ui/user-nav.tsx
  src/components/user-auth-form.tsx
  src/lib/api/actions.ts
  src/lib/api/agreements.ts
  src/lib/api/coaching-relationships.ts
  src/lib/api/coaching-sessions.ts
  src/lib/api/entity-api.ts
  src/lib/api/organizations.ts
  src/lib/api/overarching-goals.ts
  src/lib/api/user-session.ts
  src/lib/api/user-sessions.ts
  src/types/action.ts
  src/types/agreement.ts
  src/types/coaching-session.ts
  src/types/coaching_relationship_with_user_names.ts
  src/types/general.ts
  src/types/user-session.ts
Labels: enhancement

#90 Add a collapsible sidebar, replacing the top menu-bar
  package-lock.json
  package.json
  src/app/coaching-sessions/[id]/layout.tsx
  src/app/coaching-sessions/[id]/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/hooks/use-mobile.tsx
  src/components/hooks/use-mutation-observer.ts
  src/components/lib/utils.ts
  src/components/ui/alert-dialog.tsx
  src/components/ui/app-sidebar.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/card.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/coaching-sessions/actions-list.tsx
  src/components/ui/coaching-sessions/overarching-goal.tsx
  src/components/ui/command-menu.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/main-nav-menu.tsx
  src/components/ui/main-nav.tsx
  src/components/ui/mobile-nav.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/organization-switcher.tsx
  src/components/ui/popover.tsx
  src/components/ui/preset-selector.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/site-header.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/slider.tsx
  src/components/ui/switch.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/tooltip.tsx
  src/components/user-auth-form.tsx
  src/lib/stores/organization-state-store.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: enhancement, feature work

#89 88 feature add member management page
  src/app/organizations/[id]/members/layout.tsx
  src/app/organizations/[id]/members/page.tsx
  src/components/ui/dashboard/coaching-session-list.tsx
  src/components/ui/members/add-member-button.tsx
  src/components/ui/members/add-member-dialog.tsx
  src/components/ui/members/member-card.tsx
  src/components/ui/members/member-container.tsx
  src/components/ui/members/member-list.tsx
  src/components/ui/user-nav.tsx
  src/components/user-auth-form.tsx
  src/lib/api/actions.ts
  src/lib/api/agreements.ts
  src/lib/api/coaching-relationships.ts
  src/lib/api/coaching-sessions.ts
  src/lib/api/entity-api.ts
  src/lib/api/organizations.ts
  src/lib/api/organizations/users.ts
  src/lib/api/overarching-goals.ts
  src/lib/api/user-sessions.ts
  src/lib/api/users.ts
  src/types/user-session.ts
  src/types/user.ts
Labels: feature work

#92 88 feature add member management page add users
  src/app/organizations/[id]/members/layout.tsx
  src/components/ui/app-sidebar.tsx
  src/components/ui/members/add-member-dialog.tsx
  src/components/ui/members/member-container.tsx
  src/components/ui/organization-selector.tsx
  src/lib/api/entity-api.ts
  src/types/user.ts
Labels: feature work
