Repository refactor-group/refactor-platform-fe, pull requests merged in 2025-04, with the labels that each got.

#95 Add Delete User
  package-lock.json
  src/app/organizations/[id]/members/page.tsx
  src/components/ui/members/member-card.tsx
  src/components/ui/members/member-container.tsx
  src/components/ui/members/member-list.tsx
  src/lib/api/actions.ts
  src/lib/api/agreements.ts
  src/lib/api/coaching-relationships.ts
  src/lib/api/coaching-sessions.ts
  src/lib/api/entity-api.ts
  src/lib/api/organizations.ts
  src/lib/api/organizations/users.ts
  src/lib/api/overarching-goals.ts
  src/lib/api/user-sessions.ts
  src/lib/api/users.ts
Labels: feature work

#100 Delete coaching sessions
  src/components/ui/coaching-session.tsx
  src/components/ui/dashboard/coaching-session-list.tsx
Labels: feature work

#103 Coaching session page tweaks
  src/app/coaching-sessions/[id]/page.tsx
  src/components/ui/coaching-session-selector.tsx
  src/components/ui/coaching-sessions/overarching-goal-container.tsx
  src/components/ui/site-header.tsx
Labels: enhancement

#106 Create a shared PageContainer component
  src/app/dashboard/page.tsx
  src/app/organizations/[id]/members/page.tsx
  src/components/ui/dashboard/dashboard-container.tsx
  src/components/ui/page-container.tsx
Labels: enhancement

#99 82 feature request suggestion create fe image workflow
  .github/workflows/build_and_push_image.yml
  .gitignore
  Dockerfile
  README.md
  docs/runbooks/Container-README.md
Labels: feature work

#98 Add link to coaching notes editor
  package-lock.json
  package.json
  src/app/coaching-sessions/[id]/page.tsx
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/coaching-sessions/coaching-notes/extended-link-extension.tsx
  src/components/ui/coaching-sessions/coaching-notes/extensions.tsx
  src/components/ui/coaching-sessions/coaching-notes/link-dialog.tsx
  src/components/ui/coaching-sessions/coaching-notes/toolbar.tsx
  src/styles/styles.scss
Labels: enhancement, feature work

#109 Fix issue with link that is also strikethrough, and fix outdated link tooltip text
  src/components/ui/coaching-sessions/coaching-notes.tsx
  src/components/ui/coaching-sessions/coaching-notes/extended-link-extension.tsx
Labels: enhancement
